# Generated by Django 5.0.3 on 2024-03-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NutritionFacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("serving_size_g", models.FloatField()),
                ("calories", models.FloatField()),
                ("protein_g", models.FloatField()),
                ("suger_g", models.FloatField()),
                ("fat_total_g", models.FloatField()),
                ("carbohydrates_total_g", models.FloatField()),
                ("cholesterol_mg", models.FloatField()),
                ("potassium_mg", models.FloatField()),
                ("sodium_mg", models.FloatField()),
                ("fiber_g", models.FloatField()),
            ],
        ),
    ]
