# Generated by Django 5.0.3 on 2024-04-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nutrition_facts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("serving_size_g", models.FloatField()),
                ("calories", models.FloatField()),
                ("protein_g", models.FloatField()),
                ("suger_g", models.FloatField()),
                ("fat_total_g", models.FloatField()),
                ("carbohydrates_total_g", models.FloatField()),
                ("cholesterol_mg", models.FloatField()),
                ("potassium_mg", models.FloatField()),
                ("sodium_mg", models.FloatField()),
                ("fiber_g", models.FloatField()),
            ],
            options={
                "ordering": ("title",),
            },
        ),
    ]
