# Generated by Django 5.0.3 on 2024-04-03 11:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nutrition_facts", "0002_ingredient"),
        ("recipes_manager", "0003_alter_ingredientrecipe_ingredient_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NutritionFacts",
        ),
    ]
