# Generated by Django 5.0.3 on 2024-04-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ("title",)},
        ),
        migrations.AlterModelOptions(
            name="ingredient",
            options={"ordering": ("title",)},
        ),
        migrations.AlterModelOptions(
            name="recipe",
            options={"ordering": ("title",)},
        ),
        migrations.AddField(
            model_name="ingredientrecipe",
            name="title",
            field=models.CharField(default="Ingredient", max_length=256),
        ),
    ]
