# Generated by Django 5.0.3 on 2024-04-03 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nutrition_facts", "0002_ingredient"),
        (
            "recipes_manager",
            "0002_alter_category_options_alter_ingredient_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredientrecipe",
            name="ingredient",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="nutrition_facts.ingredient",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                through="recipes_manager.IngredientRecipe",
                to="nutrition_facts.ingredient",
            ),
        ),
        migrations.DeleteModel(
            name="Ingredient",
        ),
    ]
